### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by marekp97** [rn-bridge/react-native-geofencing#9] opened 2024-12-02 13:31 UTC
Hi, I have a question, is it possible to add JavaVersion.VERSION_17 in build.gradle?
```
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
```
My application won't build with 1_8:
```
Execution failed for task ':rn-bridge_react-native-geofencing:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (17).
```

Maybe I can set something so that older libraries also work with this one?

**Comment by HarshaR1642** [comment] 2024-12-03 17:07
@marekp97 Can you try setting the following in your build.gradle ?
`
kotlinOptions {
    jvmTarget = "1.8"
}
`

**Comment by marekp97** [comment] 2024-12-03 17:14
No, then I get an error:
```
Gradle DSL method not found: 'kotlinOptions()'
Possible causes:
Your project may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
```
My react-native version: 0.72

**Comment by sriharshamadamanchi** [comment] 2024-12-03 17:51
@marekp97 Can you try setting the same in library build.gradle as i was not able to reproduce the issue ?
kotlinOptions { jvmTarget = "1.8" }

**Comment by marekp97** [comment] 2024-12-03 18:23
@sriharshamadamanchi Yes, adding `kotlinOptions { jvmTarget = "1.8" }` in the library solves the problem too. Can you add it in build.gradle to the new version?

**Comment by sriharshamadamanchi** [comment] 2024-12-04 09:43
@marekp97 New version 1.0.3 is released with above change

**Closed** 2024-12-04 09:55 UTC

**Comment by marekp97** [comment] 2025-01-22 12:32
Hello, in version 1.0.4 you removed:
`kotlinOptions { jvmTarget = "1.8" }`

And now the library doesn't work again...

**Comment by HarshaR1642** [comment] 2025-01-22 12:37
@marekp97 Some projects are using Java 8 and some are Java 17. To support both i have removed jvmTarget from library. You can add jvmTarget to your projects `app/build.gradle` either 8 or 17.

**Comment by marekp97** [comment] 2025-01-22 13:10
@HarshaR1642 But if I add it there then other libraries that have a lower version stop working...

**Comment by sriharshamadamanchi** [comment] 2025-01-22 19:35
@marekp97 I will add the jvm target again
